name: Azure Secret Rotation
on:
  schedule:
    - cron: '0 0 1 */5 *'  # Run every 5 months
  workflow_dispatch:        # Allow manual triggering

jobs:
  rotate-secrets:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: write
    steps:
      - uses: actions/checkout@v2
      
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Update Azure Publish Profile
        run: |
          echo "Rotating Azure publish profile..."
          profile=$(az webapp deployment list-publishing-profiles \
            --name academease-contact \
            --resource-group academease-rg \
            --query "[?publishMethod=='MSDeploy']" \
            --output json)
          echo "::add-mask::"
          echo "AZURE_WEBAPP_PUBLISH_PROFILE=$profile" >> $GITHUB_ENV
      
      - name: Update GitHub Secret
        uses: Azure/github-actions-secret-setter@v1
        with:
          name: 'AZURE_WEBAPP_PUBLISH_PROFILE'
          value: ${{ env.AZURE_WEBAPP_PUBLISH_PROFILE }}
          repo-token: ${{ secrets.PAT_TOKEN }}
